### ISSUE TITLE
可不可以自定义 lint 规范呢？

### ISSUE THREAD

**Issue by ghost** [lingochamp/okcheck#12]
比如 某个写法错误，review 没有发现，某种写法会出现错误，可以以后自动检查。

**Comment by Jacksgong** [comment]
可以的，集成的所有的静态扫描，基本上每一种都有自己的配置方式，就拿android lint来说，你可以参照[官方文档](https://developer.android.com/studio/write/lint?hl=zh-CN#lint.xml-%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B)加以配置。
