### ISSUE TITLE
求助:配置不对吗?

### ISSUE THREAD

**Issue by weinierfei** [lingochamp/okcheck#3]
![image](https://user-images.githubusercontent.com/11873816/41080438-10ad96a8-6a59-11e8-8f74-656df6a16838.png)
配置入上图;
插件版本
`
classpath 'com.liulishuo.okcheck:gradle:0.2.0'
`

错误信息:
![image](https://user-images.githubusercontent.com/11873816/41080800-b1359638-6a5a-11e8-8292-e4f4f95365ad.png)
 
-------------------------------------
去掉
```
exclude = ['**/proto/*.java']
destination = project.rootProject.buildDir
```
错误信息:
![image](https://user-images.githubusercontent.com/11873816/41080536-9ab24380-6a59-11e8-9244-1c798af8b4b2.png)

我是不是哪儿用的不对?

**Comment by Jacksgong** [comment]
实际上如果正常使用，都是默认值的话是不需要做任何特殊设置的，引入既完成配置。不过这里的几个值，上层接口确实存在问题，这边在0.2.1会进行修复。

**Comment by Jacksgong** [comment]
感谢你提出该问题，已经在0.2.1上已经修复，这里存在三个问题:

1. `exclude`中存在一个问题(coverage配置不包含`exclude`)
2. `findbugs`中不是`excludeBugFilter`而是`excludeFilter`(已在readme中修复)
3. `unittest`没有`exclude`(已在readme中修改)
